make:
	g++ -c main.cpp bazookaTower.cpp boat.cpp bullet.cpp button.cpp enemy.cpp freezeTower.cpp game.cpp gameStates.cpp gunTower.cpp mainMenuState.cpp map.cpp mapSelectorState.cpp state.cpp tile.cpp tower.cpp wave.cpp player.cpp endGameState.cpp
	g++ -o main main.o bazookaTower.o boat.o bullet.o button.o enemy.o freezeTower.o game.o gameStates.o gunTower.o mainMenuState.o map.o mapSelectorState.o state.o tile.o tower.o wave.o player.o endGameState.o -lsfml-graphics -lsfml-window -lsfml-system

clean:
	-rm *.o